name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create .env
      run: cp .env.example .env
    - name: Create .env.test
      run: cp .env.test.example .env.test
    - name: Create public.pem
      run: cp keys/public.pem.example keys/public.pem
    - name: Create private.pem
      run: cp keys/private.pem.example keys/private.pem
    - name: Build docker images
      run: docker compose build
    - name: Run docker images
      run: docker compose up -d
    - name: Run tests
      run: docker exec -t blogs-tester npm run test
    - name: Clean up
      if: success() || failure()
      run: docker compose down --rmi all -v --remove-orphans